"""initial model v17

Revision ID: 90dd050fabf3
Revises: 
Create Date: 2023-07-03 15:15:40.401902

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '90dd050fabf3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('brands',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('brand_name', sa.String(length=100), nullable=True),
    sa.Column('brand_image_url', sa.Text(), nullable=True),
    sa.Column('created_by', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('modified_by', sa.BigInteger(), nullable=True),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('brand_name')
    )
    op.create_table('category',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('category_name', sa.String(length=255), nullable=False),
    sa.Column('created_by', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('modified_by', sa.BigInteger(), nullable=True),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('category_name')
    )
    op.create_table('roles',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('role_name', sa.String(length=20), nullable=False),
    sa.Column('created_by', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('modified_by', sa.BigInteger(), nullable=True),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('role_name')
    )
    op.create_table('sub_category',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('sub_category_name', sa.String(length=255), nullable=False),
    sa.Column('category_id', sa.BigInteger(), nullable=True),
    sa.Column('image_url', sa.Text(), nullable=True),
    sa.Column('created_by', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('modified_by', sa.BigInteger(), nullable=True),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sub_category_name')
    )
    op.create_table('users',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('username', sa.String(length=20), nullable=False),
    sa.Column('fullname', sa.String(length=250), nullable=False),
    sa.Column('email', sa.String(length=250), nullable=False),
    sa.Column('mobile_number', sa.String(length=13), nullable=False),
    sa.Column('adhaar_number', sa.String(length=12), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('House_number', sa.String(length=255), nullable=False),
    sa.Column('landmark', sa.String(length=255), nullable=False),
    sa.Column('pincode', sa.BigInteger(), nullable=False),
    sa.Column('city', sa.String(length=255), nullable=False),
    sa.Column('state', sa.String(length=255), nullable=False),
    sa.Column('Role', sa.BigInteger(), nullable=True),
    sa.Column('created_by', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('modified_by', sa.BigInteger(), nullable=True),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['Role'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('product',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('product_name', sa.String(length=255), nullable=False),
    sa.Column('whole_sale_price', sa.BigInteger(), nullable=False),
    sa.Column('price', sa.BigInteger(), nullable=False),
    sa.Column('quantity', sa.BigInteger(), nullable=False),
    sa.Column('base_unit', sa.String(length=250), nullable=False),
    sa.Column('discount', sa.BigInteger(), nullable=False),
    sa.Column('sub_category_id', sa.BigInteger(), nullable=True),
    sa.Column('brand_id', sa.BigInteger(), nullable=True),
    sa.Column('product_description', sa.Text(), nullable=True),
    sa.Column('created_by', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('modified_by', sa.BigInteger(), nullable=True),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['brand_id'], ['brands.id'], ),
    sa.ForeignKeyConstraint(['sub_category_id'], ['sub_category.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('product_image',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('image_name', sa.String(length=255), nullable=True),
    sa.Column('product_id', sa.BigInteger(), nullable=True),
    sa.Column('created_by', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('modified_by', sa.BigInteger(), nullable=True),
    sa.Column('modified_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('product_image')
    op.drop_table('product')
    op.drop_table('users')
    op.drop_table('sub_category')
    op.drop_table('roles')
    op.drop_table('category')
    op.drop_table('brands')
    # ### end Alembic commands ###
